### ISSUE TITLE
Feature Request: Ability to mark slow tests

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-astropy#21]
This comes up from time to time: How do I mark a test as slow on `astropy`?

Such tests are usually performance or stress tests, which we could opt to run in a cron but definitely not for every push event. For example, in astropy/astropy#9182 , @aarchiba wrote a stress test for caching behavior with multiprocessing (which she had to scale down for push events).

There is a nice example for `--runslow` at https://docs.pytest.org/en/latest/example/simple.html but AFAIK not provided by `pytest` "out of the box".

A similar request but for doctest is at astropy/pytest-doctestplus#51 .

Also, STScI already have something like this, which I would be happy to move upstream if you want:

https://github.com/spacetelescope/ci_watson/blob/00c902e8fecdcb624494d1248cc13af29dbddd5d/ci_watson/plugin.py#L16-L21

**Comment by bsipocz** [comment]
We would also need this in astroquery, the current workaround is a manual hack.

**Comment by aarchiba** [comment]
I thought I had seen this idea - designate slow tests for separate running when appropriate - in scipy as well, but I can't see any sort of machinery there so maybe I was wrong. 

The pytest example isn't built in but seems pretty simple and effective. More, it seems like the extensive part - the part that needs to be distributed all over the source code - is pretty unambiguous and simple: just stick a @pytest.mark.slow in front of every test that needs it. (We even already report the worst offenders!) It follows the pattern established by the remote_data mark as well, and like that we could have degrees of slowness (flagged with different marks or an argument). 

The machinery to select which tests to run is localized and easily changed after the fact. The choice about how (and whether) to integrate slow tests into CI is even further down the road and more easily changed.

So a first-pass PR would just stick in a proof-of-concept test runner hack and start flagging tests as slow, then document the flag (and criteria for it) and encourage people to be willing to write slower, more thorough tests when appropriate. 

In the long run the work should probably spawn something in astropy helpers that could be used in some kind of portable way. (All sorts of scientific package can benefit from slow tests, for example generating data sets big enough for good statistics.) But there's probably a chicken-and-egg problem: this isn't exciting work when there are no extra tests to run this way, and there's no point flagging or even writing slow tests until infrastructure exists so that they don't make the test suite useless. So I recommend (and am willing to take a swing at, once the feature freeze frenzy dies down) writing some simple runner setup and then filling out some tests.

**Comment by bnavigator** [comment]
Closed by #48?

**Comment by pllim** [comment]
Yes, thanks for the ping! 😸

**Comment by bsipocz** [comment]
@pllim - did we really manage to close this twice?
