### ISSUE TITLE
Too many dependencies? Remove mock and hypothesis?

### ISSUE THREAD

**Issue by mhvk** [astropy/pytest-astropy#32]
It seems both astropy and the testing framework have started to draw in an inordinate number of dependencies. I'm quite happy with our own ones, as these are under our own control, but feel any beyond need an extremely strong rationale to be included, and if there is no such rationale, they can still be used but should be among the "optional tests" category. For me, yes, `cov` should be included, but I see no strong reason for either `mock` or `hypothesis` - indeed, the first test file that uses `hypothesis` has now caused multiple issues, partially because hypothesis is evolving fast. I do feel that with each new package, we're just spreading our development brains more thinly.

I'll open a PR if there is agreement that we should have core and optional testing dependencies.

**Comment by astrofrog** [comment]
Mock is definitely not needed since it is now part of the standard library in Python 3.x! (unittest.mock)

**Comment by astrofrog** [comment]
For hypothesis, it's somewhat concerning if things are already breaking - I would have assumed it would be pretty stable by now. Maybe worth pinning it to a major version rather than removing as a dependency? (pinging @zac-hd in case he has any thoughts about this)

**Comment by mhvk** [comment]
Well, we just added the first tests a week ago or so. The problem seems to be that we pin to `>5.1` when really we needed a higher version for the tests we added.

**Comment by mhvk** [comment]
But the point of this issue was a more general one, that we should have a *minimal* set of test requirements, just like we have a minimal set of regular dependencies. I don't think `pytest-astropy` is the place to include bells and whistles - it is used also by affiliated packages which should not have to draw in too many things. (I may well change my mind once we have more experience with `hypothesis`, but I don't think we're there yet.)

**Comment by mhvk** [comment]
p.s. The hypothesis version issue is trickier than I thought: `hypothesis 5.16` should be good enough. Anyway, irrelevant for here.

**Comment by Zac-HD** [comment]
@astrofrog - Hypothesis is fanatical about backwards compatibility, and you're already on the current major version.

I wouldn't even say we're evolving fast - while every pull request is released as a new version, almost all of those are small bugfixes, internal changes, or interface improvements. The newest significant feature is targeted testing, from [October last year](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-38-0), and replacing that with a no-op would leave you with working tests (albeit somewhat less effective and with worse reporting of errors).

**Comment by Cadair** [comment]
> Mock is definitely not needed since it is now part of the standard library in Python 3.x! (unittest.mock)

pytest-mock is not unittest.mock it's pytest fixtures which provide a much nicer way of mocking things.

**Comment by Cadair** [comment]
I requested pytest-mock be added for sunpy, as we also use pytest-astropy. It's a super lightweight package, maintained under the pytest GH org, with no additional deps or anything.

I don't see that there should be any issues with it, and also I don't see any issues in installing more pytest plugins (of reasonable quality) where they are useful.

Also please don't remove hypothesis from pytest-astropy because sunpy now relies on it existing here.

**Comment by mhvk** [comment]
If it is for sunpy, then why not add it to your test dependencies? I do think that like for our regular dependencies, we should aim for a minimum of truly required ones, not just everything that perhaps is handy. What is wrong with creating your own `pytest-sunpy`, which depends on `pytest-astropy` and gathers in a few further useful dependencies? As is, because sunpy finds it useful, now every affiliated package has to draw in the same things.

p.s. Sorry in advance for being rather grumpy about this! I just have spent way too much time in the last weeks dealing with testing problems. Indeed, this goes back a month and is the reason we now have an issue in astropy to think about 4.2 being one of consolidation, instead of making an every more fragile structure (see https://github.com/astropy/astropy/issues/10352). I do think we need to slow down making changes to our infrastructure.

**Comment by mhvk** [comment]
See also https://github.com/astropy/astropy/issues/10342 - Of required and optional dependencies.

**Comment by bsipocz** [comment]
I'm with @Cadair here. `pytest-astropy` might need more frequent releases, but it better has everything needed for testing, given all of these are lightweight. As for `pytest-mock`, it's tiny, and may also become useful for astroquery.

The `hypothesis` issue unfortunately came from the fact that adding it to `pytest-astropy` happened much earlier than wrapping up the actual astropy core PRs that use it. To avoid any such hickups in the future, we could add a pytest-astropy minversion that also uses the minversions of the `pytest-astropy` components, to the astropy core oldest version test job.

 > I do feel that with each new package, we're just spreading our development brains more thinly.

There is a reason why these roles are full time roles on professional software teams, testing and running stuff smoothly might seem trivial and easily dismissible for astronomers (yes, I was at the receiving end of plenty of dismissive comments about it within the astropy team, and while we're at it neither devops nor qa engineering is listed as a role on an otherwise extremely detailed list, just to show how much these are really valued...). 

Anyway, I don't really see what the suggestion would be here. Astropy core already depends on `hypothesis`. If it's not part of `pytest-astropy`, then instead of installing, and keeping `pytest-astropy` up-to-date, developers would need to install both `pytest-astropy` and `hypothesis`. Or we should have a much more complicated test setup where not all tests are run depending on missing testing infrastructure dependencies. While I see the value in keeping the package thin on run time dependencies for users, I firmly believe that developers should have all test dependencies that are possibly used in the subpackages they are developing for, otherwise we would only run into issues only present on CI but not locally.

On the other hand, if it's easy to keep `hypothesis` as an optional dependency, I would be OK with removing it from here (similarly to `pytest-mpl` that is not being included due to it's mpl dependency).

**Comment by mhvk** [comment]
Yes, in my grumpy morning I was referring to making `hypothesis` optional to astropy. But perhaps that goes too far. Anyway, I'm definitely happy to defer to both of you here. For my own packages, I'll just stop relying on `pytest-astropy` and instead put in just the parts of it that I need.

**Comment by bsipocz** [comment]
> For my own packages, I'll just stop relying on pytest-astropy and instead put in just the parts of it that I need

For individual packages, I think that's a good balance. Maybe it should even be the approach the package template suggests by default, with a note that the metapackage `pytest-astropy` also exists, but its primary goal is to serve big library needs, so it brings in many dependencies that may look blackboxy.

**Comment by pllim** [comment]
Some clarification on the purpose and scope of this metapackage would be nice indeed. In my simpler packages, I also find it too "heavy" to use.

**Comment by mhvk** [comment]
I've now moved on for my own packages, but I'll add that I ended up essentially excluding just the dependencies that are not based at astropy, i.e., I now have basically a list of the actual pytest plugins hosted here.

Anyway, I certainly don't want to increase the burden of packaging astropy further, and it is fine if this package is simply one part that helps avoid that.
