### ISSUE TITLE
Bump Python minversion to 3.10?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-astropy#57]
Looks like it is still 3.7 which seems super old.

https://github.com/astropy/pytest-astropy/blob/fd6589aecef426d59a399d5a6446bf187b53e4bf/setup.cfg#L30

**Comment by bsipocz** [comment]
Are there any practical reasons for this? I think in general the rule of thumb is to support more versions with the tooling that what SPEC0 would call for unless there is a strong argument due to a missing feature in the older version.

So, I'm 👎 on this jump all the way to 3.10, particularly because e.g. in pyvo and astroquery we still support older versions (3.8+) (mostly to support users on LTS distros), and it would be a pity to not be able to pick up any updates from these helper libraries due their very conservative version bumps.

**Comment by pllim** [comment]
What about just bumping to `>=3.8`?

**Comment by bsipocz** [comment]
I'm all good with that one.

**Comment by dhomeier** [comment]
As an aside, from the Numpy discussion thread on dropping 3.9:
> Current numbers (as of May 4th) for downloads of manylinux wheels:
> * 2.7: 2%
> * 3.5: 0.3%
> * 3.6: 7.4%
> * 3.7: 20.4%
> * 3.8: 23.0%
> * 3.9: 15.3%
> * 3.10: 20.8%
> * 3.11: 8.4%
> * 3.12: 2.3%
